# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, git
, terraform
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "14pd2v6mahjm17pn3xz0kjiwcvg427dr4rq5nwhaiz4vj8a57yzq";
    armv6l-linux = "0dpmap74kkazpav7ks7fvhd5j8cv75xj8rlhwwszhzkzh8dgc17l";
    aarch64-linux = "1nqg4wgalsjis2k7z30q4yiirlk60cxyfyx18lhsp6s6lrzs7vcs";
    x86_64-darwin = "09ysfaypm1hfk9a8pn1l4546m0x5h55aqkwrr7k9syp1m84p9wv9";
    aarch64-darwin = "1fb6xmlbn9bf89901fr4927sa1adzviysmr689ki1qvn32iixl02";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.24.0/mach-composer-2.24.0-linux-amd64.tar.gz";
    armv6l-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.24.0/mach-composer-2.24.0-linux-armv6.tar.gz";
    aarch64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.24.0/mach-composer-2.24.0-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.24.0/mach-composer-2.24.0-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.24.0/mach-composer-2.24.0-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mach-composer";
  version = "2.24.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./bin/mach-composer $out/bin/mach-composer
    wrapProgram $out/bin/mach-composer --prefix PATH : ${lib.makeBinPath ([ git terraform ])}
  '';
  postInstall = ''
    installShellCompletion --cmd mach-composer \
    --bash <($out/bin/mach-composer completion bash) \
    --fish <($out/bin/mach-composer completion fish) \
    --zsh <($out/bin/mach-composer completion zsh)
  '';

  system = system;

  meta = {
    description = "Orchestration tool for modern MACH ecosystems, powered by Terraform infrastructure-as-code underneath";
    homepage = "https://www.machcomposer.io/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
