# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, git
, terraform
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "09dqglm1c403p8smwwvdiw6480gx6288aa7hi0rq1iridgw38160";
    armv6l-linux = "0xsl7zv65qp2mz1in3v6338fx0y6jqbk9dvc5b9n5scznslm214q";
    aarch64-linux = "0imkkq26kv3x2xv8m5jjmdlc5dzl5qy5vzcw3xq891vnmp2rg8yi";
    x86_64-darwin = "1810l2amrg70y23kf1c1wvyag08nf19gdzzf24x37676wrmp6chx";
    aarch64-darwin = "0ib4qvsq2cj4nakqmzpcbp32c2m6ykgl3byr3i37bxqqhqp0h346";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.2/mach-composer-2.21.2-linux-amd64.tar.gz";
    armv6l-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.2/mach-composer-2.21.2-linux-armv6.tar.gz";
    aarch64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.2/mach-composer-2.21.2-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.2/mach-composer-2.21.2-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.2/mach-composer-2.21.2-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mach-composer";
  version = "2.21.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./bin/mach-composer $out/bin/mach-composer
    wrapProgram $out/bin/mach-composer --prefix PATH : ${lib.makeBinPath ([ git terraform ])}
  '';
  postInstall = ''
    installShellCompletion --cmd mach-composer \
    --bash <($out/bin/mach-composer completion bash) \
    --fish <($out/bin/mach-composer completion fish) \
    --zsh <($out/bin/mach-composer completion zsh)
  '';

  system = system;

  meta = {
    description = "Orchestration tool for modern MACH ecosystems, powered by Terraform infrastructure-as-code underneath";
    homepage = "https://www.machcomposer.io/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
