# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, git
, terraform
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "06jl7mksyrasmz5cwlzpysbbaxv9mrrircj216ib0nd71r9r4is1";
    armv6l-linux = "0lrj7nzpj375m0xxc1v8shxf0frr682098575llz0gwm950ajvin";
    aarch64-linux = "0pm152140384d4bshnyzy6ww6bd15rdb5390kp29dz0pjxd447qc";
    x86_64-darwin = "0mfyc92axjccv6nxy5zfccrm6m43h49lpxnyxmldx9h1a0y4i6br";
    aarch64-darwin = "1a69zwa7xas45mfgg6qn0kh53iinjayxzkb0jdd5n4jmsirhzfjr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.0/mach-composer-2.21.0-linux-amd64.tar.gz";
    armv6l-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.0/mach-composer-2.21.0-linux-armv6.tar.gz";
    aarch64-linux = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.0/mach-composer-2.21.0-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.0/mach-composer-2.21.0-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.21.0/mach-composer-2.21.0-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mach-composer";
  version = "2.21.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./bin/mach-composer $out/bin/mach-composer
    wrapProgram $out/bin/mach-composer --prefix PATH : ${lib.makeBinPath ([ git terraform ])}
  '';
  postInstall = ''
    installShellCompletion --cmd mach-composer \
    --bash <($out/bin/mach-composer completion bash) \
    --fish <($out/bin/mach-composer completion fish) \
    --zsh <($out/bin/mach-composer completion zsh)
  '';

  system = system;

  meta = {
    description = "Orchestration tool for modern MACH ecosystems, powered by Terraform infrastructure-as-code underneath";
    homepage = "https://www.machcomposer.io/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
